#%RAML 1.0
title: test

/CustomerName:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                [{"customerName": "Dave", "customerName": "John"}